[2025-09-16T11:44:59.615+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-16T11:44:59.644+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag2.v2.0.hello_user scheduled__2025-09-09T03:00:00+00:00 [queued]>
[2025-09-16T11:44:59.663+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag2.v2.0.hello_user scheduled__2025-09-09T03:00:00+00:00 [queued]>
[2025-09-16T11:44:59.664+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-09-16T11:44:59.694+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): hello_user> on 2025-09-09 03:00:00+00:00
[2025-09-16T11:44:59.715+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag2.v2.0', 'hello_user', 'scheduled__2025-09-09T03:00:00+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmp7bktm43h']
[2025-09-16T11:44:59.722+0000] {standard_task_runner.py:105} INFO - Job 159: Subtask hello_user
[2025-09-16T11:44:59.725+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=208) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-16T11:44:59.727+0000] {standard_task_runner.py:72} INFO - Started process 220 to run task
[2025-09-16T11:44:59.817+0000] {task_command.py:467} INFO - Running <TaskInstance: dag2.v2.0.hello_user scheduled__2025-09-09T03:00:00+00:00 [running]> on host 4461bcf72552
[2025-09-16T11:44:59.993+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag2.v2.0' AIRFLOW_CTX_TASK_ID='hello_user' AIRFLOW_CTX_EXECUTION_DATE='2025-09-09T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-09T03:00:00+00:00'
[2025-09-16T11:44:59.995+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-16T11:45:00.068+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-09-16T11:45:00.086+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-16T11:45:00.087+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag2.v2.0, task_id=hello_user, run_id=scheduled__2025-09-09T03:00:00+00:00, execution_date=20250909T030000, start_date=20250916T114459, end_date=20250916T114500
[2025-09-16T11:45:00.145+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-16T11:45:00.187+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-16T11:45:00.192+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
